// Traces the masks `icons.py` renders into `src/ui/aircraftIcons.ts`.
//
//   NODE_PATH=<dir with potrace and pngjs installed> node tools/models/trace-icons.mjs MASK_DIR id ...
//
// Every jet is traced on the same canvas at the same scale, and the view box
// is cut to what the largest of them needs, so the icons keep their sizes
// relative to one another.

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(path.join(process.env.NODE_PATH ?? ".", "noop.js"));
const potrace = require("potrace");
const { PNG } = require("pngjs");

const [maskDir, ...jets] = process.argv.slice(2);
const MARGIN = 6;

function lit(file, canopy) {
  const png = PNG.sync.read(readFileSync(file));
  const at = (x, y) => {
    const i = (y * png.width + x) * 4;
    // The body is white on transparent; the canopy white on black.
    return canopy ? png.data[i] > 127 : png.data[i + 3] > 127;
  };
  return { png, at };
}

function bounds(file, canopy) {
  const { png, at } = lit(file, canopy);
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (let y = 0; y < png.height; y += 1) {
    for (let x = 0; x < png.width; x += 1) {
      if (!at(x, y)) continue;
      minX = Math.min(minX, x); maxX = Math.max(maxX, x);
      minY = Math.min(minY, y); maxY = Math.max(maxY, y);
    }
  }
  return { minX, minY, maxX, maxY, width: png.width, height: png.height };
}

function trace(file, canopy) {
  // Potrace wants dark on light: paint the mask black on white.
  const { png, at } = lit(file, canopy);
  const out = new PNG({ width: png.width, height: png.height });
  for (let y = 0; y < png.height; y += 1) {
    for (let x = 0; x < png.width; x += 1) {
      const i = (y * png.width + x) * 4;
      const value = at(x, y) ? 0 : 255;
      out.data[i] = out.data[i + 1] = out.data[i + 2] = value;
      out.data[i + 3] = 255;
    }
  }
  const buffer = PNG.sync.write(out);
  return new Promise((resolve, reject) => {
    potrace.trace(buffer, { threshold: 128, turdSize: 4, optTolerance: 0.3, alphaMax: 1 }, (error, svg) => {
      if (error) return reject(error);
      const d = /\sd="([^"]+)"/.exec(svg)?.[1] ?? "";
      resolve(d.replace(/(\d+\.\d{1})\d+/g, "$1").replace(/\s+/g, " ").trim());
    });
  });
}

const all = jets.map((jet) => bounds(path.join(maskDir, `${jet}-body.png`), false));
const box = {
  minX: Math.min(...all.map((b) => b.minX)) - MARGIN,
  minY: Math.min(...all.map((b) => b.minY)) - MARGIN,
  maxX: Math.max(...all.map((b) => b.maxX)) + MARGIN,
  maxY: Math.max(...all.map((b) => b.maxY)) + MARGIN,
};
// Square, centred on the canvas, so every jet sits in the middle of its tile.
const centre = all[0].width / 2;
const half = Math.max(centre - box.minX, box.maxX - centre, centre - box.minY, box.maxY - centre);

const icons = {};
for (const jet of jets) {
  icons[jet] = {
    body: await trace(path.join(maskDir, `${jet}-body.png`), false),
    canopy: await trace(path.join(maskDir, `${jet}-canopy.png`), true),
  };
}

const lines = [
  "// Generated by tools/models/trace-icons.mjs from the models themselves, all",
  "// at one scale, nose up. Do not edit: re-render and re-trace instead.",
  'import type { AirframeId } from "../sim/airframes";',
  "",
  `export const AIRCRAFT_ICON_VIEWBOX = "${Math.floor(centre - half)} ${Math.floor(centre - half)} ${Math.ceil(2 * half)} ${Math.ceil(2 * half)}";`,
  "",
  "export const AIRCRAFT_ICONS: Record<AirframeId, { body: string; canopy: string }> = {",
  ...jets.map((jet) => `  ${jet}: {\n    body: "${icons[jet].body}",\n    canopy: "${icons[jet].canopy}",\n  },`),
  "};",
  "",
];
writeFileSync("src/ui/aircraftIcons.ts", lines.join("\n"));
console.log("traced", jets.join(", "), "viewBox", Math.ceil(2 * half));
